### ISSUE TITLE
Do not update and depend on meta columns throughout the catalog

### ISSUE THREAD

**Issue by alangumer** [avorg/audioverse-api#1]
There are several areas through out the admin catalog where meta column values throughout the catalog are updated when any part of it is modified.

There is a helper named UpdateMetaColumns.php

Tasks
- [ ] Find and write support code for this change in admin Admin
- [ ] Find and write support code for this change in Public Webiste
- [ ] Find and write support code for this change in Public API
- [ ] Find and write support code for this change in Laravel API

**Comment by pobrejuanito** [comment]
@alangumer I am not clear what needs to be done. Can you briefly describe what this issue is about?

**Comment by alangumer** [comment]
@pobrejuanito take a look to those tables, you will find that they have fields for data related to other tables, for example, catalogRecordings has fields for sponsorTitle, sponsorLogo, conferenceTitle, conferenceLogo, seriesTitle, seriesLogo, speakerNamesGnfCasual, etc. those fields are redundant/duplicated, because those fields are present in their respective catalog table, in this case the table catalogRecordings should only have the ids (Foreign Keys) to reference those tables.

This change may need admin and avorg site modifications.

**Comment by pobrejuanito** [comment]
@Henry Orozco <henry@audioverse.org> Yes, I see. You want to join
referencing tables to fetch those piece of information. You want this
change reflected in all places that depends on those fields? Like api,
public website, and admin?

**Comment by alangumer** [comment]
@pobrejuanito yes.

**Comment by avorg** [comment]
Since these catalogs tables are tightly integrated in the admin website, api, and audioverse website, it has been decided to don't modify them in order to don't disrupt our current systems, that being said, any new developments should not use those meta columns, instead should get the data by joining other tables, and once we have moved onto the new systems, we can get rid of those columns.
